services:
  # Frontend (React + Nginx)
  travel-photo:
    build: .
    container_name: travel-photo-app
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - shared-network  # Dùng chung network với backend đang chạy

networks:
  shared-network:
    external: true